- app/models/post.rb
- app/models/user.rb
- db/migrate/20191118135338_create_posts.rb
- db/schema.rb
- test/models/post_test.rb
Created the post model with migration
> Created the post model with migration

- app/controllers/posts_controller.rb
- app/models/post.rb
- app/views/posts/index.html.erb
- config/routes.rb
- db/schema.rb
- db/seeds.rb
- test/controllers/posts_controller_test.rb
Done with adding controller to post
> Done with adding controller to post

- app/controllers/posts_controller.rb
- app/views/layouts/application.html.erb
- app/views/posts/_form.html.erb
- app/views/posts/edit.html.erb
- app/views/posts/index.html.erb
- app/views/posts/new.html.erb
- app/views/posts/show.html.erb
- db/schema.rb
- db/seeds.rb
Done with adding all the views for model post
> Done with adding all the views for model post

- .gitignore
- app/controllers/posts_controller.rb
- app/models/post.rb
- app/views/posts/index.html.erb
Added the delete option to post index page
> Added the delete option to post

- app/models/category.rb
- app/models/post.rb
- app/models/post_category.rb
- db/migrate/20191119105225_create_categories.rb
- db/migrate/20191119110838_create_post_categories.rb
- db/schema.rb
- test/models/category_test.rb
- test/models/post_category_test.rb
- test/models/postcategory_test.rb
Added two new models category and post_category
> Added two new models category and post_category

- app/controllers/application_controller.rb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- devise views created for both sign-up and log-in (migration)
- applied bootstrap to both forms
- customized sign-up form
- note: image as string as Amanda recommended
> sign-up modified

- app/controllers/application_controller.rb
- app/controllers/post_votes_controller.rb
- app/controllers/posts_controller.rb
- app/views/posts/show.html.erb
- config/routes.rb
- test/controllers/post_votes_controller_test.rb
- votes controller 
- application controller fix
- voting link
> add post vote controller

- app/controllers/comments_controller.rb
- app/models/user.rb
- app/views/comments/_show.html.erb
- config/routes.rb
Done with the deleting the comments
> Done with the deleting the comments

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_voting_card.scss
- app/models/post.rb
- app/views/posts/_card.html.erb
- app/views/posts/show.html.erb
- config/application.rb
> voting cards

- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/pages/_global.scss
- app/assets/stylesheets/pages/_index.scss
- app/views/posts/index.html.erb
"Added the buttons and card in components"
> Create card component

- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/components/_card.scss
- app/views/posts/index.html.erb
> Add button component fill

- Gemfile
- Gemfile.lock
- app/controllers/posts_controller.rb
- app/models/category.rb
- app/models/comment.rb
- app/models/post.rb
- app/models/post_category.rb
- app/models/post_option.rb
- app/models/post_vote.rb
- app/models/user.rb
- app/views/posts/_form.html.erb
- app/views/posts/show.html.erb
- db/seeds.rb
- test/models/category_test.rb
- test/models/comment_test.rb
- test/models/post_category_test.rb
- test/models/post_option_test.rb
- test/models/post_test.rb
- test/models/post_vote_test.rb
- test/models/user_test.rb
- simple form updated
- dependencies updated
- post controller updated
- seeds updated
> categories

- app/views/posts/show.html.erb
> hmtl alignment|show page

- app/controllers/posts_controller.rb
- app/models/post.rb
- app/views/posts/_form.html.erb
- app/views/shared/_navbar.html.erb
- post controller modified | count action added 
- nav_bar modified  | filtering logic linked to buttons
> filter vote counts and date

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/pages/_global.scss
- app/controllers/posts_controller.rb
- app/views/posts/index.html.erb
- db/seeds.rb
Added the image vertically with padding
> Added the image vertically with padding

- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/components/_card.scss
- app/controllers/posts_controller.rb
- app/views/posts/_form.html.erb
- app/views/posts/index.html.erb
Completed the categorybar in the index
> Completed the categorybar in the index

- app/controllers/posts_controller.rb
- app/models/post.rb
- app/views/posts/index.html.erb
fixed the category on the index page
> fixed the category on the index page

- app/assets/stylesheets/components/_card.scss
- app/views/posts/index.html.erb
Need to fix the index page of the post
> Need to fix the index page of the post

- app/views/posts/index.html.erb
- app/views/shared/_index-photo-card.html.erb
- app/views/shared/_index-text-card.html.erb
Created an index page with text card and photo card
> Created an index page with text card and photo card

- app/assets/stylesheets/components/_card.scss
- app/models/category.rb
- app/views/posts/_form.html.erb
- app/views/shared/_index-photo-card.html.erb
- app/views/shared/_index-text-card.html.erb
> Added the text-card to index

- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_dashboard.scss
- app/controllers/pages_controller.rb
- app/views/pages/dashboard.html.erb
-  dashboard cards 
- dashboard / category buttons (filters)
> Dash board cards

- app/assets/stylesheets/components/_category-checkbox.scss
- app/assets/stylesheets/components/_index.scss
- app/javascript/packs/application.js
- app/views/posts/_form.html.erb
Styled the checkboxes of the category
> Styled the checkboxes of the category

- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/components/_card.scss
> heart buttons centered

- app/assets/stylesheets/components/_alert.scss
- app/views/layouts/application.html.erb
- app/views/post_votes/create.js.erb
"Added the alert in the center"
> Added the alert in the center

- Gemfile
- Gemfile.lock
- app/views/layouts/application.html.erb
- db/seeds.rb
- seeds | faker comments for posts
> faker comments for posts

- app/views/shared/_navbar.html.erb
- db/seeds.rb
- dropdown menu category colors modified
> category colors updated | drop down menu modified

- app/views/layouts/application.html.erb
- config/routes.rb
- package-lock.json
- package.json
- show for each post matches category color on body
> category background colors matches

- Gemfile.lock
- app/controllers/api/v1/base_controller.rb
- app/controllers/api/v1/users_controller.rb
- app/controllers/application_controller.rb
- app/models/user.rb
- app/views/shared/_bottom-buttons.html.erb
- app/views/shared/_notifications.js.erb
- config/routes.rb
"Done with making the notification dynamic"
> Notification dynamic

- app/javascript/components/touch.js
- app/javascript/packs/application.js
- package.json
- yarn.lock
"Added double tap and hold javascript"
> Added double tap and hold javascript

- Gemfile.lock
- app/assets/stylesheets/components/_showpage_components.scss
- app/views/comments/_show.html.erb
- db/seeds.rb
- yarn.lock
- comments styled
- trash can icon added
> comments styled | font awesome trash can added

- app/assets/stylesheets/components/_showpage_components.scss
- app/views/posts/show.html.erb
> show page resize font and margin bottom

- app/javascript/components/touch.js
- app/views/shared/_index-photo-card.html.erb
- app/views/shared/_index-text-card.html.erb
Added double tap and hold on text as well
> Added double tap adn hold on text as well

- app/views/pages/dashboard.html.erb
- app/views/shared/_bottom-buttons.html.erb
- app/views/shared/_navbar.html.erb
- db/seeds.rb
- renamed category "professional" to "work"
- changed random profile image to hardcoded pickle Rick
> profile image and cat. name replacement

- app/views/posts/index.html.erb
- app/views/posts/show.html.erb
- username changes for sponsored cards
> sponsored posts details

- app/assets/stylesheets/components/_showpage_components.scss
- app/views/posts/edit.html.erb
- show page improved
- delete title in editing page
> styling of show post

- app/views/layouts/application.html.erb
- app/views/shared/_notifications.js.erb
Deleted the annoying alert messages
> Deleted the annoying alert messages

- app/assets/stylesheets/components/_alert.scss
Done with fixing the alert on the show page
> Done with fixing the alert on the show page

- app/views/devise/registrations/edit.html.erb
> edit your profile page stylized

- app/javascript/components/touch.js
- app/javascript/packs/application.js
Deleted event listener on hold
> Deleted event listener on hold

- db/seeds.rb
> decreased number of seeds
